# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('isbn', models.BigIntegerField()),
                ('author', models.CharField(max_length=70)),
                ('publicationDate', models.DateField()),
                ('publisher', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TextbookPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postTitle', models.CharField(max_length=70)),
                ('condition', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=70)),
                ('sold', models.BooleanField(default=False)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Textbook')),
            ],
        ),
    ]
