# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='publicationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='publisher',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
