# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendations',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recommended_items', models.CharField(max_length=100)),
            ],
        ),
    ]
