# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20170215_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookpost',
            name='postDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='textbookpost',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
