# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20170508_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='id',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='marketplace.TextbookPost'),
        ),
    ]
