# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20170508_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='listing',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
