haproxy:
    build: ./haproxy
    container_name: haproxy
    volumes:
       - ./haproxy:/app
    ports:
       - "8000:8000"
    links:
       - web1:web1
       - web2:web2

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
        - .:/app
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python batch.py"

models:
    container_name: models
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations marketplace && python manage.py migrate && python manage.py loaddata db.json && python manage.py test marketplace &&
        mod_wsgi-express start-server --working-directory . --reload-on-changes ./models/wsgi.py"


exp:
   container_name: exp
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
   volumes:
      - ./exp:/app
   command: bash -c "pip install requests && python setup.py && mod_wsgi-express start-server --log-to-terminal --working-directory . --reload-on-changes ./exp/wsgi.py"

web1:
   container_name: web1
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8003:8000"
   volumes:
      - ./web:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --log-to-terminal --working-directory . --reload-on-changes ./web/wsgi.py"

web2:
   container_name: web2
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8004:8000"
   volumes:
      - ./web:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --log-to-terminal --working-directory . --reload-on-changes ./web/wsgi.py"
