models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./:/app
    ports:
      - "8001:8000"

    command: bash -c "mod_wsgi-express start-server --log-to-terminal --working-directory . --reload-on-changes ./uvaTextbookExchange/wsgi.py"
#    command: bash -c "python manage.py loaddata db.json"
